### ISSUE TITLE
Make Cursor compatible with Collection[Dict[str, Any]]

### ISSUE THREAD

**Issue by ThibaultLemaire** [mongodb-labs/pymongo-stubs#11]
```python
from pymongo.cursor import Cursor
from typing import Collection, Dict, Any

class MyCursor(Collection[Dict[str, Any]], Cursor):  # error: Definition of "__iter__" in base class "Iterable" is incompatible with definition in base class "Cursor"  [misc]
  ...
```

This is because `Cursor.__iter__` returns a `Cursor` which isn't an `Iterator[...]` (and therefore is incompatible).

**Comment by ShaneHarvey** [comment]
Thanks for reporting this! I would expect mypy to consider Cursor an Iterator because it has the appropriate `__next__` and `__iter__` methods which should satisfy the iterator protocol: https://docs.python.org/3/library/stdtypes.html#iterator.__iter__

This is an easy fix though. We'll need to change Cursor/CommandCursor like this:
```
-    def __iter__(self) -> Cursor: ...
+    def __iter__(self) -> Iterator[_DocumentOut]: ...
```

**Comment by ThibaultLemaire** [comment]
Yes I was checking the source in `cursor.py` and I came to the same conclusion, but I was surprised that Cursor doesn't explicitely inherit from Sequence/Collection/Iterator¹ so these issues could be detected by directly running mypy on this project (I don't know how you're testing `pymongo-stubs`).

Also, I noticed `_DocumentOut` is an alias for Any, when it should really be something like 

```python
JSON = Union[Dict[str, "JSON"], List["JSON"], str, int, float, bool, None]
```

although that's [not supported yet](https://github.com/python/mypy/issues/731) (I guess you already know that), but I believe we could make a compromise and type it at least as `Dict[str, Any]`. Unless I'm missing something?

¹: Sequence makes the most sense but the signature for `.count()` doesn't seem to be compatible

**Comment by ShaneHarvey** [comment]
We don't directly inherit from Iterator because pymongo-stubs uses structural subtyping not nominal subtyping: https://docs.python.org/3/library/typing.html#nominal-vs-structural-subtyping

The `_DocumentOut=Any` issue is described in https://jira.mongodb.org/browse/PYTHON-2427. We could change it to `MutableMaping[str, Any]` but that would be incorrect because clients can be configured to return [RawBSONDocument](https://pymongo.readthedocs.io/en/stable/api/bson/raw_bson.html?highlight=raw_bson) which is immutable. Please let me know your thoughts.

**Comment by ThibaultLemaire** [comment]
I wasn't aware that you could configure clients to return raw BSON. I understand the Any now. Okay then I guess it's not worth the trouble (and can't be considered part of the current issue anyway).

One would have to make the `CodecOptions`, `MongoClient`, `Database`, et al. be generic over `document_class` ...

**Comment by ShaneHarvey** [comment]
> One would have to make the CodecOptions, MongoClient, Database, et al. be generic over document_class ...

Yes, unfortunately I was unable to implement the "generic over document_class" idea. I don't remember exactly what the blocker was, maybe something about namedtuple+generics. Typing/mypy support is ever improving so it may be more feasible now. It could be more feasible to make Collection generic but default `dict` (the most common document_class). However as far as I know typing does not allow for default types for generics, ie. if the generic type is omitted it always becomes `Any`.

Going back to the Cursor `__iter__` issue, would you like to work on a PR to fix the bug? We'll need to change both Cursor and CommandCursor like this:
```python
-    def __iter__(self) -> Cursor: ...
+    def __iter__(self) -> Iterator[_DocumentOut]: ...
```

**Comment by ShaneHarvey** [comment]
I'm going to close this since I think the original issue was either a bug in mypy itself or a bug in the app code. It would be great if you could report the issue to mypy. I opened https://github.com/mongodb-labs/pymongo-stubs/issues/15 to investigate if there is a better alternative for _DocumentOut that we can use.
